config/routes.rb
R20130214Cookbook::Application.routes.draw do

resources :books, :recipes, :ingredients

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many :recipes


end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
attr_accessible  :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id
  #recipe has two relationships. with books AND ingredients. 1-many and many-many
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def create
    book= Book.create(params[:book]) #create a book object and redirect to that utl of the new object.
    redirect_to(book) #this is the id page where we see the book you created.
  end

  def new
    @book= Book.new #duh, we want a blank objet so people will fill params into them
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book= Book.find(params[:id]) #from the url after clicking link on the index.
  end

  def update
    book= Book.find(params[:id]) #object
    book.update_attributes(params[:book])
    redirect_to(book)
  end

  def destroy
    book= Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients= Ingredient.all #all ingredient objects. time to iterate through the array.
  end

  def create
    ingredient = Ingredient.create(params[:id])
    redirect_to(ingredient)
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
      @ingredient = Ingredient.find(params[:id]) #just edit.
  end

  def show
    @ingredient= Ingredient.find(params[:id])
  end

  def update #no form for this.
    ingredient= Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end

  def destroy
    ingredient= Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes= Recipe.all
  end

  def create
    recipe = Recipe.create(params[:id])
    redirect_to(recipe)
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe= Recipe.find(params[:id])

  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    recipe= Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end

  def destroy
    recipe= Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
<br>
<%= f.label :title, :autofocus => 'autofocus' %>
<%= f.text_field :title %>

<%= f.label :cuisine %>
<%= f.text_field :cuisine %>

<%= f.label :image, 'Image URL' %>
<%= f.text_field :image %>
<br>
<% Recipe.all.each do |recipe| %>
  <span><%= recipe.name %> </span>
  <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>  <%# [] means array of recipe ids %>
<% end %>
<br>

<%= f.submit %>

<% end %>

app/views/books/edit.html.erb
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<ol>

<% @books.each do |book| %>
<ul>

  <li><%= link_to(book.title, book) %> </li>
  <li> Primal : <%= book.cuisine %> </li>
  <li> Author/Chef Extraordinaire : <%= book.chef %> </li>
  <%= image_tag(book.image) %>
</ul>

<% end %>
<ul>

</ol>

<%# object knows that show page is coming. show method coming next. it goes to the id next in the route ) %>

app/views/books/new.html.erb
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%= link_to(@book.title, @book) %>
  <br>
  <p> Cuisine: <%= @book.cuisine %> </p>
   <p> Chef: <%= @book.chef %> </p>
  <div id= 'bookpic'><%= image_tag(@book.image) %></div>

  <%= link_to 'delete', @book, :method => :delete, :confirm => 'will you actually delete this?' %> <%# you have to specify delete but not edit. that's cuz it's not a post or get %>

  <%= link_to 'edit', edit_book_path(@book) %>

  <br>
<div class="recipe">
  <% @book.recipes.each do |recipe| %> <%# array of recipe objetcs...for each object do %>
        <p> recipe: <%= recipe.name %></p>
        <%= image_tag(recipe.image) %>

        <br>

        <% recipe.ingredients.each do |ingredient| %>
            <p><%= ingredient.name %></p>
            <p><%= image_tag(ingredient.image) %></p>

          <% end %>


      <% end %></div>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>

<%= f.label :name, :autofocus => 'autofocus' %>
<%= f.text_field :name %>

<%= f.label :measurement %>
<%= f.text_field :measurement %>

<%= f.label :image, 'Image URL' %>
<%= f.text_field :image %>

<%= f.label :cost, 'Cost' %>
<%= f.text_field :cost %>

<%= f.submit %>

<% end %>

app/views/ingredients/edit.html.erb
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
  <% @ingredients.each  do |ingredient| %>


    <p><%= link_to(ingredient.name, ingredient) %></p>
    <p><%= ingredient.name %></p>
    <p><%= image_tag(ingredient.image) %></p>

   <% end %>

app/views/ingredients/new.html.erb
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
    <p><%= @ingredient.name %></p>
    <p><%= image_tag(@ingredient.image) %></p>

<%= link_to 'edit', edit_ingredient_path(@ingredient) %>


<%= link_to 'delete', @ingredient, :method => :delete, :confirm => 'will you actually delete this?' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130214Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav nav-tabs">
  <li class="active">
    <a href= 'books_path'>Home</a>
  </li>
  <li><%= link_to('new book', new_book_path) %></li>
  <li><%= link_to('new recipe', new_recipe_path) %></li>
  <li><%= link_to('new ingredient', new_ingredient_path) %></li>





<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

<%= f.label :name, :autofocus => 'autofocus' %>
<%= f.text_field :name %>

<%= f.label :cooktime %>
<%= f.text_field :cooktime %>

<%= f.label :image, 'Image URL' %>
<%= f.text_field :image %>

<%= f.label :instructions, 'instructions' %>
<%= f.text_field :instructions %>

<%= f.label :course %>
<%= f.text_field :course %>

<%= f.submit %>

<% end %>

app/views/recipes/edit.html.erb
<%= render :partial => 'form' %>

app/views/recipes/new.html.erb
<%= render :partial => 'form' %>